# Generated by Django 4.0.3 on 2023-03-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('cookNo', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('ingredient', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberNo', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('Id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favNo', models.AutoField(primary_key=True, serialize=False)),
                ('input', models.CharField(max_length=200, null=True)),
                ('cookNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneyo.cook')),
                ('memberNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneyo.member')),
            ],
        ),
    ]
