# Generated by Django 4.0.3 on 2023-03-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneyo', '0002_alter_member_options_alter_member_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Id',
            field=models.CharField(default='default_id_value', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
