# Generated by Django 4.0.3 on 2023-03-22 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oneyo', '0003_member_id_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberNo',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
